import hydra
from hydra import initialize_config_module, compose
from pathlib import Path

from arbitration_pdm.ego_agent import EgoAgent

import matplotlib

# Prevent matplotlib from trying to use any Xwindows backend
matplotlib.use("Agg")

# Location of paths with all simulation configs
SIM_CONFIG_PATH = "nuplan.planning.script.config.simulation"
SIM_CONFIG_NAME = "default_simulation"
# Location of paths with all nuBoard configs
NUBOARD_CONFIG_PATH = "nuplan.planning.script.config.nuboard"
NUBOARD_CONFIG_NAME = "default_nuboard"
# Select simulation parameters
CHALLENGE = "closed_loop_reactive_agents"  # [open_loop_boxes, closed_loop_nonreactive_agents, closed_loop_reactive_agents]

# Initialize configuration management system
hydra.core.global_hydra.GlobalHydra.instance().clear()  # reinitialize hydra if already initialized
with initialize_config_module(config_module=SIM_CONFIG_PATH):
    # Compose the configuration
    cfg = compose(
        config_name=SIM_CONFIG_NAME,
        overrides=[
            "experiment_name=arbitration_pdm",
            f"+simulation={CHALLENGE}",
            "scenario_filter=val14_split",
            "scenario_builder=nuplan",
            "enable_simulation_progress_bar=true",
            "worker=ray_distributed",
            "worker.threads_per_node=160",
            "distributed_mode=SINGLE_NODE",
            "number_of_gpus_allocated_per_simulation=0.05",
            "hydra.searchpath=[pkg://tuplan_garage.planning.script.config.common, pkg://tuplan_garage.planning.script.config.simulation, pkg://nuplan.planning.script.config.common, pkg://nuplan.planning.script.experiments]",
        ],
    )

import nest_asyncio
from nuplan.planning.script.run_simulation import run_simulation as main_simulation

nest_asyncio.apply()

planner = EgoAgent()

main_simulation(cfg, planners=planner)

print(f"Simulation results are saved in: {cfg.output_dir}")

# *.nuboard file generated by the simulation
simulation_file = [
    str(file)
    for file in Path(cfg.output_dir).iterdir()
    if file.is_file() and file.suffix == ".nuboard"
]

# Initialize configuration management system
hydra.core.global_hydra.GlobalHydra.instance().clear()  # reinitialize hydra if already initialized
with initialize_config_module(config_module=NUBOARD_CONFIG_PATH):
    # Compose the configuration
    cfg = compose(
        config_name=NUBOARD_CONFIG_NAME,
        overrides=[
            "scenario_builder=nuplan_mini",  # set the database (same as simulation) used to fetch data for visualization
            f"simulation_path={simulation_file}",  # nuboard file path, if left empty the user can open the file inside nuBoard
        ],
    )

# Run nuBoard
from nuplan.planning.script.run_nuboard import main as main_nuboard

main_nuboard(cfg)
