[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "mosaic"
version = "0.1.0"
description = "Arbitration Graphs meet PDM trajectory planning"
authors = [
    {name = "Marlon Steiner", email = "marlon.steiner@kit.edu" },
    {name = "Nick Le Large", email = "nick.lelarge@kit.edu"}
]
readme = "README.md"
requires-python = ">=3.9.12"
dependencies = [
    "arbitration_graphs >=2.0.0",
    "flow-drive",
    "interplan",
    "nuplan-devkit",
    "tuplan-garage",
]

[project.scripts]
mosaic = "mosaic.cli.main:cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["mosaic*"]

[tool.setuptools.package-data]
"mosaic" = ["**/*.yaml"]

[tool.uv.sources]
nuplan-devkit = { git = "https://github.com/ll-nick/nuplan-devkit" }
tuplan-garage = { git = "https://github.com/ll-nick/tuplan_garage" }
flow-drive = { path = "../flowdrive" }
interplan = { git = "https://github.com/ll-nick/interPlan" }

[tool.uv]
override-dependencies = [
    # Flowdrive and nuplan-devkit have conflicting dependencies, so we need to override them here
    "pytorch-lightning==2.0.1",
    "torch==2.8.0",
    "torchvision==0.23.0",
]
prerelease = "allow"

